pipeline {
    agent any

    stages {
        stage('Git-clone') {
            steps {
                git 'https://github.com/Shahul123-kicha/mavenproject.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
         stage('Package') {
            steps {
                bat 'mvn Package'
            }
        }
    }
}
