pipeline {
    agent any

    stages {
        stage('Git-clone') {
            steps {
                git 'https://github.com/Shahul123-kicha/mavenproject.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
